export const errorInput: string;
export const errorText: string;
export const fullPage: string;
export const gatsby: string;
export const gatsbyFocusWrapper: string;
export const highlightText: string;
export const mainPage: string;
export const mainVideo: string;
export const pitchPhrase: string;
